version: 1

linters:
  enable:
    - gofmt
    - govet
    - goimports
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - errcheck

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  sort-results: true 