site_name: Kontraktor Documentation
site_description: Documentation for Kontraktor - A builder-helper for environment configuration, secret aggregation, and developer task automation
site_author: Kontraktor Team
repo_url: https://github.com/kontraktor-sh/kontraktor
repo_name: kontraktor-sh/kontraktor

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: /kontraktor/
  - Getting Started:
    - Installation: /kontraktor/getting-started/installation/
    - Quick Start: /kontraktor/getting-started/quickstart/
  - User Guide:
    - Taskfile Format: /kontraktor/user-guide/taskfile-format/
    - Environment Variables: /kontraktor/user-guide/environment-variables/
    - Secret Management: /kontraktor/user-guide/secret-management/
    - Task Execution: /kontraktor/user-guide/task-execution/
  - Advanced Topics:
    - Azure Key Vault Integration: /kontraktor/advanced/azure-keyvault/
    - Task Dependencies: /kontraktor/advanced/task-dependencies/
    - Importing Tasks: /kontraktor/advanced/importing-tasks/
  - Contributing:
    - Development Guide: /kontraktor/contributing/development/
    - Code of Conduct: /contributing/code-of-conduct/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true 