# api/openapi/kontraktor.yaml
openapi: "3.1.0"
info: { title: Kontraktor API, version: 0.1.0 }
paths:
  /healthz:
    get:
      operationId: healthz
      responses:
        "200": { description: OK }
