name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -o kontraktor-darwin-amd64 ./cmd/kontraktor
          GOOS=darwin GOARCH=arm64 go build -o kontraktor-darwin-arm64 ./cmd/kontraktor
          GOOS=linux GOARCH=amd64 go build -o kontraktor-linux-amd64 ./cmd/kontraktor
          GOOS=linux GOARCH=arm64 go build -o kontraktor-linux-arm64 ./cmd/kontraktor
          GOOS=windows GOARCH=amd64 go build -o kontraktor-windows-amd64.exe ./cmd/kontraktor

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kontraktor-darwin-amd64
            kontraktor-darwin-arm64
            kontraktor-linux-amd64
            kontraktor-linux-arm64
            kontraktor-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}